-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.productos
(
    id serial,
    categoria_id integer,
    nombre character varying(255),
    precio numeric(13, 2),
    existencia integer,
    desripcion text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.categorias
(
    id serial,
    nombre text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.imagenes
(
    id serial,
    producto_id integer,
    imagen text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.etiquetas
(
    id serial,
    producto_id integer,
    nombre text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id serial,
    nombre character varying(255),
    apellido character varying(255),
    correo text[],
    telefono character varying[],
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    id serial,
    nombre character varying(255),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.usuarios_roles
(
    usuario_id integer,
    rol_id integer,
    PRIMARY KEY (usuario_id, rol_id)
);

CREATE TABLE IF NOT EXISTS public.calificaciones
(
    usuario_id integer,
    producto_id integer,
    calificacion smallint,
    PRIMARY KEY (usuario_id, producto_id)
);

ALTER TABLE IF EXISTS public.productos
    ADD CONSTRAINT fk_categoria_id FOREIGN KEY (categoria_id)
    REFERENCES public.categorias (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.imagenes
    ADD CONSTRAINT fk_producto_id FOREIGN KEY (producto_id)
    REFERENCES public.productos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.etiquetas
    ADD CONSTRAINT fk_producto_id FOREIGN KEY (producto_id)
    REFERENCES public.productos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.usuarios_roles
    ADD CONSTRAINT usuario_id FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.usuarios_roles
    ADD CONSTRAINT rol_id FOREIGN KEY (usuario_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.calificaciones
    ADD CONSTRAINT usuario_id FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.calificaciones
    ADD CONSTRAINT producto_id FOREIGN KEY (producto_id)
    REFERENCES public.productos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;